import { v4 as uuidv4 } from 'uuid';
const Data = [
  {
    id: 1,
    refId: 0,
    userName: 'سید پلنگ',
    date: '16 خرداد 1401',
    time: '14:53',
    body: 'انگولار فارسی وجود ندارد. در دوره هیولای جاوااسکریپت همه؟',
    liked: false,
    disLiked: false,
    likeCount: 15,
    disLikeCount: 0,
    userImg: '',
    email: '',
  },
  {
    id: 2,
    refId: 0,
    userName: 'سید پلنگ',
    date: '16 خرداد 1401',
    time: '14:53',
    body: 'انگولار فارسی وجود ندارد. در دوره هیولای جاوااسکریپت همه؟',
    liked: false,
    disLiked: false,
    likeCount: 0,
    disLikeCount: 0,
    userImg: '',
    email: '',
  },
  {
    id: 3,
    refId: 1,
    userName: 'سید پلنگ',
    date: '16 خرداد 1401',
    time: '14:53',
    body: 'انگولار فارسی وجود ندارد. در دوره هیولای جاوااسکریپت همه؟',
    liked: false,
    disLiked: false,
    likeCount: 0,
    disLikeCount: 0,
    userImg: '',
    email: '',
  },
  {
    id: 4,
    refId: 1,
    userName: 'سید پلنگ',
    date: '16 خرداد 1401',
    time: '14:53',
    body: 'انگولار فارسی وجود ندارد. در دوره هیولای جاوااسکریپت همه؟',
    liked: false,
    disLiked: false,
    likeCount: 0,
    disLikeCount: 0,
    userImg: '',
    email: '',
  },
];

export default Data;
