import { v4 as uuidv4 } from "uuid";
import reactIcon from "../../../Assets/img-user-panel/React-icon.svg";
const Data = [
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "1ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "2ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "3ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "4ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "5ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "6ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "7ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "8ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "9ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "10ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 20000000000,
    data: "1401/05/12",
  },
  {
    id: uuidv4(),
    icon: reactIcon,
    name: "11ری اکت مقدماتی تا پیشرفته",
    teacher: "بحرالعلوم",
    price: 200000,
    data: "1401/05/12",
  },
];

export default Data;
